### ISSUE TITLE
Is there any 'get last-row' proc ?

### ISSUE THREAD

**Issue by lanius412** [mashingan/excelin#6]
Now, I use following script

```
import excelin

proc getLastRow(sheet: Sheet, col: string):int =
 var rowNum:int = 1
  
 type tmp = object
 while sizeof(tmp) == 1:
   let value = sheet.row(rowNum).getCell[:string](col)
   if value == "":
     break
   inc(rowNum)
 result = rowNum - 1

if isMainModule:
  let excel = readExcel("src.xlsx")
  let sheet = excel.getSheet(excel.sheetNames()[0])

  let lastRow = sheet.getLastRow("A")
  echo lastRow
```

but, If there is a blank cell between cells with values, this proc will not work.

**Comment by mashingan** [comment]
Currently there's no API to get the last row but we can provide it for next version.  
However, for the last-cell in particular row, this is quite tricky since internally the Excel holds the information based on row instead of column. After looking at your script, perhaps you might need the last-cell in row too.

**Comment by lanius412** [comment]
Yes, I know the last-cell
On my sheet, last-row of each col is the same. So I didn't need to consider.
Thank you

**Comment by mashingan** [comment]
Should be added in `v0.5.0` . Check the  [common operations example](https://github.com/mashingan/excelin#common-operations) (before the end) to see how it works.  

Since this changes some internal rows/cells, please comment or open new issue if there's regression. Thanks.
